# Translations template for PROJECT.
# Copyright (C) 2023 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2023.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2023-02-21 11:10+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.11.0\n"

#: launch_worker.py:48 launch_worker_splitter.py:48
msgid "FILE_UPLOADED"
msgstr ""

#: src/backend/verifier_exports.py:85 src/backend/verifier_exports.py:88
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/verifier_exports.py:154 src/backend/verifier_exports.py:157
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/splitter.py:412
#: src/backend/controllers/splitter.py:418 src/backend/verifier_exports.py:309
#: src/backend/verifier_exports.py:315 src/backend/verifier_exports.py:321
msgid "EXPORT_MEM_ERROR"
msgstr ""

#: src/backend/verifier_exports.py:316
msgid "PDF_FILE_NOT_FOUND"
msgstr ""

#: src/backend/verifier_exports.py:327
msgid "MEM_WS_INFO_WRONG"
msgstr ""

#: src/backend/controllers/splitter.py:424 src/backend/verifier_exports.py:333
msgid "MEM_WS_INFO_EMPTY"
msgstr ""

#: src/backend/classes/MEMWebServices.py:38
msgid "HOST_NOT_FOUND"
msgstr ""

#: src/backend/classes/SMTP.py:218
msgid "RESET_PASSWORD"
msgstr ""

#: src/backend/classes/SMTP.py:220
msgid "FORGOT_EMAIL_HEADER"
msgstr ""

#: src/backend/classes/SMTP.py:220
msgid "CLICK_HERE"
msgstr ""

#: src/backend/classes/SMTP.py:220
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""

#: src/backend/controllers/accounts.py:45 src/backend/models/accounts.py:61
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:58 src/backend/models/accounts.py:84
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:85
#: src/backend/controllers/accounts.py:174
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:112
#: src/backend/controllers/accounts.py:205
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:137
#: src/backend/controllers/accounts.py:143
msgid "UPDATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:229
#: src/backend/controllers/accounts.py:235
#: src/backend/controllers/accounts.py:259
#: src/backend/controllers/accounts.py:265 src/backend/models/accounts.py:130
msgid "UPDATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:289 src/backend/models/accounts.py:150
msgid "CREATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:330
#: src/backend/controllers/accounts.py:336 src/backend/models/accounts.py:170
msgid "CREATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:337
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:357 src/backend/controllers/user.py:214
#: src/backend/models/accounts.py:234 src/backend/models/accounts.py:257
#: src/backend/models/accounts.py:276 src/backend/models/user.py:204
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:399
#: src/backend/controllers/accounts.py:405 src/backend/models/accounts.py:298
msgid "UPDATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:434
#: src/backend/controllers/accounts.py:440 src/backend/models/accounts.py:318
msgid "CREATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:441
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:455
#: src/backend/controllers/accounts.py:461 src/backend/models/accounts.py:340
msgid "DELETE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:476
#: src/backend/controllers/accounts.py:482 src/backend/models/accounts.py:192
msgid "DELETE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:504
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:79
#: src/backend/controllers/artificial_intelligence.py:393
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:103
msgid "CREATE_IA_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:114
msgid "UPDATE_IA_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:394
#: src/backend/models/artificial_intelligence.py:59
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/auth.py:105
msgid "RESET_JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:138 src/backend/controllers/auth.py:185
#: src/backend/controllers/auth.py:230 src/backend/controllers/auth.py:277
#: src/backend/controllers/auth.py:288 src/backend/controllers/auth.py:298
#: src/backend/controllers/auth.py:325 src/backend/rest/auth.py:69
msgid "LOGIN_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:206 src/backend/controllers/auth.py:245
#: src/backend/controllers/auth.py:253 src/backend/controllers/auth.py:256
#: src/backend/controllers/auth.py:258
msgid "JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:253
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""

#: src/backend/controllers/auth.py:289
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr ""

#: src/backend/controllers/auth.py:313
msgid "LDAP_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:314 src/backend/models/auth.py:140
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr ""

#: src/backend/controllers/auth.py:340
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:352
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:364
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:387 src/backend/controllers/auth.py:572
#: src/backend/controllers/auth.py:628 src/backend/controllers/auth.py:643
#: src/backend/controllers/auth.py:651 src/backend/controllers/auth.py:657
msgid "LDAP_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:388
msgid "LOGIN_LDAP_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:560 src/backend/controllers/auth.py:566
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:562 src/backend/controllers/auth.py:568
#: src/backend/controllers/auth.py:574 src/backend/controllers/auth.py:580
#: src/backend/controllers/auth.py:586
msgid "LDAP_SYNCHRO_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:578 src/backend/controllers/auth.py:584
#: src/backend/controllers/auth.py:663 src/backend/rest/auth.py:110
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr ""

#: src/backend/controllers/auth.py:626 src/backend/controllers/auth.py:641
#: src/backend/controllers/auth.py:649
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr ""

#: src/backend/controllers/auth.py:661 src/backend/rest/auth.py:108
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr ""

#: src/backend/controllers/config.py:61
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:77
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:93
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:109
msgid "RETRIEVE_REGEX_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:121 src/backend/controllers/config.py:141
#: src/backend/controllers/config.py:153 src/backend/controllers/config.py:173
#: src/backend/models/config.py:199 src/backend/models/config.py:223
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr ""

#: src/backend/controllers/config.py:122 src/backend/controllers/config.py:154
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr ""

#: src/backend/controllers/config.py:194 src/backend/models/config.py:245
msgid "UPDATE_REGEX_ERROR"
msgstr ""

#: src/backend/controllers/config.py:214 src/backend/models/config.py:271
msgid "UPDATE_DOCSERVER_ERROR"
msgstr ""

#: src/backend/controllers/config.py:255 src/backend/controllers/config.py:265
#: src/backend/controllers/config.py:270
msgid "ERROR_UPDATING_IMAGE"
msgstr ""

#: src/backend/controllers/config.py:256 src/backend/controllers/config.py:266
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr ""

#: src/backend/controllers/config.py:271
msgid "CUSTOM_NOT_PRESENT"
msgstr ""

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:34
#: src/backend/controllers/doctypes.py:76 src/backend/models/doctypes.py:131
#: src/backend/models/doctypes.py:134
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:40 src/backend/models/doctypes.py:51
msgid "ADD_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:60
#: src/backend/controllers/doctypes.py:96
#: src/backend/controllers/doctypes.py:109
#: src/backend/controllers/doctypes.py:161
#: src/backend/controllers/doctypes.py:192
msgid "DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:128
msgid "BUNDLESEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:135
msgid "DOCUMENTSEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:154
msgid "DOCTYPESEPARATOR"
msgstr ""

#: src/backend/controllers/forms.py:46 src/backend/controllers/forms.py:56
#: src/backend/controllers/forms.py:82 src/backend/controllers/forms.py:190
msgid "FORMS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:97 src/backend/controllers/forms.py:146
#: src/backend/models/forms.py:63
msgid "GET_FORM_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:129
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:184 src/backend/controllers/forms.py:312
#: src/backend/controllers/forms.py:318
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:204 src/backend/controllers/forms.py:210
msgid "DELETE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:219 src/backend/controllers/inputs.py:102
#: src/backend/controllers/outputs.py:57
#: src/backend/controllers/positions_masks.py:160
msgid "COPY_OF"
msgstr ""

#: src/backend/controllers/forms.py:236 src/backend/controllers/forms.py:242
msgid "DUPLICATE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:256 src/backend/controllers/forms.py:262
msgid "DISABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:276 src/backend/controllers/forms.py:282
msgid "ENABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:298
msgid "GET_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:70 src/backend/controllers/inputs.py:130
#: src/backend/controllers/inputs.py:157 src/backend/controllers/inputs.py:168
#: src/backend/controllers/inputs.py:181
msgid "CREATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:71 src/backend/controllers/inputs.py:131
msgid "NOT_ALLOWED_INPUT_PATH"
msgstr ""

#: src/backend/controllers/inputs.py:84 src/backend/controllers/inputs.py:90
msgid "UPDATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:115 src/backend/controllers/inputs.py:121
msgid "DUPLICATE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:158
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:169
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:194
msgid "GET_INPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:207
msgid "GET_INPUT_BY_INPUT_ID_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:228 src/backend/controllers/inputs.py:234
msgid "DELETE_INPUT_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:270
msgid "FS_WATCHER_DELETION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:271 src/backend/controllers/inputs.py:338
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr ""

#: src/backend/controllers/inputs.py:317 src/backend/controllers/inputs.py:337
msgid "FS_WATCHER_CREATION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:318
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr ""

#: src/backend/controllers/inputs.py:343
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/inputs.py:349
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/mailcollect.py:36
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:52
msgid "UPDATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:68
msgid "CREATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:82
#: src/backend/controllers/mailcollect.py:88
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:102
#: src/backend/controllers/mailcollect.py:108
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:122
#: src/backend/controllers/mailcollect.py:128
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:142
#: src/backend/controllers/mailcollect.py:152
msgid "MAILCOLLECT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:64 src/backend/controllers/outputs.py:70
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:93 src/backend/controllers/outputs.py:115
#: src/backend/controllers/outputs.py:121
msgid "UPDATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:94
msgid "NOT_ALLOWED_OUTPUT_PATH"
msgstr ""

#: src/backend/controllers/outputs.py:145
msgid "CREATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:158
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:171
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:185
#: src/backend/controllers/outputs.py:191
msgid "DELETE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:42
#: src/backend/controllers/positions_masks.py:66
#: src/backend/controllers/positions_masks.py:125
#: src/backend/controllers/positions_masks.py:131
msgid "POSITION_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:81
#: src/backend/controllers/positions_masks.py:98
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:145
#: src/backend/controllers/positions_masks.py:151
msgid "DELETE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:176
#: src/backend/controllers/positions_masks.py:182
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:196
#: src/backend/controllers/positions_masks.py:202
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:216
#: src/backend/controllers/positions_masks.py:222
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:245
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:268
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:286
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:304
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/privileges.py:37
#: src/backend/controllers/privileges.py:65
msgid "GET_PRIVILEGES_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:47 src/backend/controllers/roles.py:53
#: src/backend/controllers/roles.py:95 src/backend/controllers/roles.py:101
#: src/backend/models/roles.py:84
msgid "UPDATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:75 src/backend/models/roles.py:104
msgid "CREATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:114
msgid "GET_ROLE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:128 src/backend/controllers/roles.py:134
msgid "DELETE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:148 src/backend/controllers/roles.py:154
msgid "DISABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:168 src/backend/controllers/roles.py:174
msgid "ENABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:91
msgid "LOAD_METADATA_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:131
#: src/backend/controllers/verifier.py:75
msgid "AT"
msgstr ""

#: src/backend/controllers/splitter.py:155
msgid "FORM_UNDEFINED"
msgstr ""

#: src/backend/controllers/splitter.py:158
msgid "CUSTOMER_UNDEFINED"
msgstr ""

#: src/backend/controllers/splitter.py:251
#: src/backend/controllers/verifier.py:345
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:361
msgid "ADD_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:496
#: src/backend/controllers/splitter.py:758
msgid "EXPORT_PDF_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:518
#: src/backend/controllers/splitter.py:783
msgid "EXPORT_XML_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:534
msgid "UPDATE_BATCH_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:547
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:560
msgid "UPDATE_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:575
#: src/backend/controllers/splitter.py:596
#: src/backend/controllers/splitter.py:611
#: src/backend/controllers/splitter.py:626
msgid "UPDATE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:640
msgid "CMIS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:653
msgid "OPENADS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:833
msgid "CHECK_FOLDER_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:851
msgid "OPENADS_ADD_DOC_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:936
#: src/backend/controllers/verifier.py:570 src/backend/models/splitter.py:572
#: src/backend/models/verifier.py:171
msgid "GET_TOTALS_ERROR"
msgstr ""

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr ""

#: src/backend/controllers/tasks_watcher.py:34
msgid "CREATE_TASK_ERROR"
msgstr ""

#: src/backend/controllers/user.py:64
msgid "CREATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:103 src/backend/controllers/user.py:120
#: src/backend/controllers/user.py:185 src/backend/models/user.py:134
#: src/backend/models/user.py:181
msgid "GET_USER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/user.py:137
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr ""

#: src/backend/controllers/user.py:159
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr ""

#: src/backend/controllers/user.py:179 src/backend/controllers/user.py:184
msgid "RESET_PASSWORD_ERROR"
msgstr ""

#: src/backend/controllers/user.py:180
msgid "RESET_TOKEN_MISMATCH"
msgstr ""

#: src/backend/controllers/user.py:235
msgid "UPDATE_PROFILE"
msgstr ""

#: src/backend/controllers/user.py:236
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:242
msgid "UPDATE_USER"
msgstr ""

#: src/backend/controllers/user.py:243
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:270 src/backend/controllers/user.py:276
#: src/backend/models/user.py:227 src/backend/models/user.py:271
msgid "UPDATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:290 src/backend/controllers/user.py:296
msgid "DELETE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:310 src/backend/controllers/user.py:316
msgid "DISABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:330 src/backend/controllers/user.py:336
msgid "ENABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:353 src/backend/controllers/user.py:359
#: src/backend/models/user.py:249
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:56 src/backend/models/verifier.py:40
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:167
#: src/backend/controllers/verifier.py:269
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:190
#: src/backend/controllers/verifier.py:287
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:213
#: src/backend/controllers/verifier.py:231
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:301
#: src/backend/controllers/verifier.py:307
msgid "DELETE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:322
#: src/backend/controllers/verifier.py:328
msgid "UPDATE_INVOICE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:470
#: src/backend/controllers/verifier.py:473
#: src/backend/controllers/verifier.py:490
#: src/backend/controllers/verifier.py:513
#: src/backend/controllers/verifier.py:514
msgid "API_INSEE_ERROR_CONNEXION"
msgstr ""

#: src/backend/controllers/verifier.py:542
msgid "VAT_NOT_VALID"
msgstr ""

#: src/backend/controllers/verifier.py:547
#: src/backend/controllers/verifier.py:548
msgid "VAT_API_ERROR"
msgstr ""

#: src/backend/models/accounts.py:108
msgid "SUPPLIER_UPDATE_ERROR"
msgstr ""

#: src/backend/models/artificial_intelligence.py:80
msgid "IA_MODEL_CREATE_ERROR"
msgstr ""

#: src/backend/models/artificial_intelligence.py:101
msgid "IA_MODEL_UPDATE_ERROR"
msgstr ""

#: src/backend/models/auth.py:43 src/backend/models/auth.py:101
#: src/backend/models/user.py:43 src/backend/rest/auth.py:70
msgid "BAD_USERNAME"
msgstr ""

#: src/backend/models/auth.py:45 src/backend/models/user.py:45
msgid "BAD_PASSWORD"
msgstr ""

#: src/backend/models/auth.py:47
msgid "USER_DELETED"
msgstr ""

#: src/backend/models/auth.py:49
msgid "USER_DISABLED"
msgstr ""

#: src/backend/models/auth.py:70 src/backend/models/auth.py:80
#: src/backend/models/roles.py:60
msgid "ROLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/auth.py:165
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/models/auth.py:211
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/auth.py:233
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:55
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:58
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr ""

#: src/backend/models/custom_fields.py:106
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:129
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/doctypes.py:54
msgid "DOCTYPE_ALREADY_EXIST"
msgstr ""

#: src/backend/models/doctypes.py:100
msgid "UPDATE_DOCTYPE_ERROR"
msgstr ""

#: src/backend/models/forms.py:86
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/forms.py:109
msgid "GET_DEFAULT_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:133
msgid "UPDATE_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:155
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/forms.py:211
msgid "ADD_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:214
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/inputs.py:60 src/backend/models/inputs.py:83
msgid "INPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/inputs.py:125
msgid "INPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/inputs.py:145
msgid "INPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/mailcollect.py:85
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:78
msgid "OUTPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:101
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:125
msgid "OUTPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:145
msgid "OUTPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:63
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:87
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:109
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:144
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:147
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/privileges.py:38 src/backend/models/privileges.py:59
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr ""

#: src/backend/models/roles.py:126
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr ""

#: src/backend/models/roles.py:148
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:78
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/splitter.py:125
msgid "UPDATE_SETTINGS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:150
msgid "INSERT_PAGE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:220
msgid "GET_BATCH_ERROR"
msgstr ""

#: src/backend/models/splitter.py:243
msgid "GET_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:265 src/backend/models/splitter.py:288
msgid "GET_PAGES_ERROR"
msgstr ""

#: src/backend/models/splitter.py:310
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:333
msgid "GET_DOCUMENT_ERROR"
msgstr ""

#: src/backend/models/splitter.py:355
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/status.py:40
msgid "NO_STATUS"
msgstr ""

#: src/backend/models/tasks_watcher.py:89
msgid "UPDATE_TASK_ERROR"
msgstr ""

#: src/backend/models/user.py:47
msgid "USER"
msgstr ""

#: src/backend/models/user.py:47
msgid "ALREADY_REGISTERED"
msgstr ""

#: src/backend/models/user.py:157
msgid "GET_USER_BY_MAIL_ERROR"
msgstr ""

#: src/backend/models/verifier.py:104 src/backend/models/verifier.py:125
msgid "INVOICE_UPDATE_ERROR"
msgstr ""

#: src/backend/rest/auth.py:45 src/backend/rest/auth.py:74
msgid "PGSQL_ERROR"
msgstr ""

#: src/backend/rest/auth.py:133 src/backend/rest/auth.py:161
#: src/backend/rest/auth.py:176
msgid "REQUEST_MODIFS_ERROR"
msgstr ""

#: src/backend/rest/auth.py:146
msgid "RETRIEVE_LOGIN_METHODS_ERROR"
msgstr ""

#: src/backend/rest/splitter.py:42 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr ""

