# Translations template for PROJECT.
# Copyright (C) 2023 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2023.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2023-10-13 16:51+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.3\n"

#: custom/edissyum/src/backend/process_queue_splitter.py:212
#: custom/edissyum/src/backend/process_queue_verifier.py:183
#: custom/test/src/backend/process_queue_splitter.py:213
#: custom/test/src/backend/process_queue_verifier.py:184
msgid "FILE_UPLOADED_WORKFLOW"
msgstr ""

#: src/backend/functions.py:37 src/backend/functions.py:48
#: src/backend/functions.py:52
msgid "NO_DATA_OR_DATA_MISSING"
msgstr ""

#: src/backend/functions.py:45
msgid "JSON_ERROR"
msgstr ""

#: src/backend/functions.py:48
msgid "IS_NOT"
msgstr ""

#: src/backend/scripting_functions.py:77
msgid "WORFKLOW_NOT_FOUND"
msgstr ""

#: src/backend/splitter_exports.py:95
msgid "OUTPUT_NOT_FOUND"
msgstr ""

#: src/backend/models/outputs.py:101 src/backend/splitter_exports.py:123
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr ""

#: src/backend/splitter_exports.py:170 src/backend/splitter_exports.py:281
msgid "EXPORT_PDF_ERROR"
msgstr ""

#: src/backend/splitter_exports.py:247 src/backend/splitter_exports.py:304
msgid "EXPORT_XML_ERROR"
msgstr ""

#: src/backend/splitter_exports.py:324
msgid "CHECK_FOLDER_ERROR"
msgstr ""

#: src/backend/splitter_exports.py:325
msgid "FOLDER_DOES_NOT_EXIST"
msgstr ""

#: src/backend/splitter_exports.py:343
msgid "OPENADS_ADD_DOC_ERROR"
msgstr ""

#: src/backend/verifier_exports.py:151 src/backend/verifier_exports.py:154
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/verifier_exports.py:353 src/backend/verifier_exports.py:356
#: src/backend/verifier_exports.py:423 src/backend/verifier_exports.py:426
msgid "PDF_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/verifier_exports.py:586 src/backend/verifier_exports.py:592
#: src/backend/verifier_exports.py:598
msgid "EXPORT_MEM_ERROR"
msgstr ""

#: src/backend/verifier_exports.py:593
msgid "PDF_FILE_NOT_FOUND"
msgstr ""

#: src/backend/verifier_exports.py:604
msgid "MEM_WS_INFO_WRONG"
msgstr ""

#: src/backend/verifier_exports.py:610
msgid "MEM_WS_INFO_EMPTY"
msgstr ""

#: src/backend/classes/MEMWebServices.py:40
msgid "HOST_NOT_FOUND"
msgstr ""

#: src/backend/classes/SMTP.py:223
msgid "RESET_PASSWORD"
msgstr ""

#: src/backend/classes/SMTP.py:225
msgid "FORGOT_EMAIL_HEADER"
msgstr ""

#: src/backend/classes/SMTP.py:225
msgid "CLICK_HERE"
msgstr ""

#: src/backend/classes/SMTP.py:225
msgid "FORGOT_EMAIL_FOOTER"
msgstr ""

#: src/backend/classes/SMTP.py:242
msgid "SMTP_TEST_SEND"
msgstr ""

#: src/backend/classes/SMTP.py:243
msgid "SMTP_TEST_SEND_BODY"
msgstr ""

#: src/backend/controllers/accounts.py:71 src/backend/models/accounts.py:61
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:84
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:111
#: src/backend/controllers/accounts.py:239
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:138
#: src/backend/controllers/accounts.py:270
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:196
msgid "SUPPLIER_UPDATED"
msgstr ""

#: src/backend/controllers/accounts.py:202
#: src/backend/controllers/accounts.py:208
msgid "UPDATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:294
#: src/backend/controllers/accounts.py:300
#: src/backend/controllers/accounts.py:325
#: src/backend/controllers/accounts.py:332 src/backend/models/accounts.py:127
msgid "UPDATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:356 src/backend/models/accounts.py:147
msgid "CREATE_ADDRESS_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:401
msgid "SUPPLIER_CREATED"
msgstr ""

#: src/backend/controllers/accounts.py:409
#: src/backend/controllers/accounts.py:415 src/backend/models/accounts.py:167
msgid "CREATE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:416
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:453 src/backend/controllers/user.py:248
#: src/backend/controllers/user.py:278 src/backend/models/accounts.py:231
#: src/backend/models/accounts.py:254 src/backend/models/accounts.py:273
#: src/backend/models/user.py:210
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:497
msgid "CUSTOMER_UPDATED"
msgstr ""

#: src/backend/controllers/accounts.py:502
#: src/backend/controllers/accounts.py:508 src/backend/models/accounts.py:295
msgid "UPDATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:536
msgid "CUSTOMER_CREATED"
msgstr ""

#: src/backend/controllers/accounts.py:544
#: src/backend/controllers/accounts.py:550 src/backend/models/accounts.py:315
msgid "CREATE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:551
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/accounts.py:567
msgid "CUSTOMER_DELETED"
msgstr ""

#: src/backend/controllers/accounts.py:572
#: src/backend/controllers/accounts.py:578 src/backend/models/accounts.py:337
msgid "DELETE_CUSTOMER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:595
msgid "SUPPLIER_DELETED"
msgstr ""

#: src/backend/controllers/accounts.py:600
#: src/backend/controllers/accounts.py:606 src/backend/models/accounts.py:189
msgid "DELETE_SUPPLIER_ERROR"
msgstr ""

#: src/backend/controllers/accounts.py:624
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:74
#: src/backend/controllers/artificial_intelligence.py:371
#: src/backend/controllers/artificial_intelligence.py:397
msgid "GET_IA_MODEL_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:98
msgid "CREATE_IA_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:120
msgid "DELETE_AI_MODEL"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:157
msgid "UPDATE_AI_MODEL"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:162
msgid "UPDATE_IA_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:224
msgid "CREATE_AI_MODEL"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:372
#: src/backend/controllers/artificial_intelligence.py:398
#: src/backend/models/artificial_intelligence.py:59
msgid "IA_MODEL_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:433
msgid "RENAME_AI_MODEL_ERROR"
msgstr ""

#: src/backend/controllers/artificial_intelligence.py:434
msgid "FILE_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/auth.py:66 src/backend/controllers/auth.py:317
#: src/backend/controllers/auth.py:376 src/backend/controllers/auth.py:386
#: src/backend/controllers/auth.py:396 src/backend/controllers/auth.py:441
msgid "JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:185
msgid "RESET_JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:194
msgid "UNIQUE_URL_JWT_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:228
msgid "LOGOUT"
msgstr ""

#: src/backend/controllers/auth.py:235 src/backend/controllers/auth.py:250
#: src/backend/controllers/auth.py:296 src/backend/controllers/auth.py:349
#: src/backend/controllers/auth.py:472 src/backend/controllers/auth.py:483
#: src/backend/controllers/auth.py:493 src/backend/controllers/auth.py:520
#: src/backend/rest/auth.py:82
msgid "LOGIN_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:251
msgid "USER_WEBSERVICE"
msgstr ""

#: src/backend/controllers/auth.py:291 src/backend/controllers/auth.py:344
msgid "LOGIN"
msgstr ""

#: src/backend/controllers/auth.py:375
msgid "SESSION_EXPIRED"
msgstr ""

#: src/backend/controllers/auth.py:386
msgid "AUTHORIZATION_HEADER_INCORRECT"
msgstr ""

#: src/backend/controllers/auth.py:396
msgid "ACCOUNT_ALREADY_LOGGED"
msgstr ""

#: src/backend/controllers/auth.py:428
msgid "FIRSTNAME"
msgstr ""

#: src/backend/controllers/auth.py:443 src/backend/controllers/auth.py:448
msgid "REST_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:444
msgid "USER_DO_NOT_EXISTS"
msgstr ""

#: src/backend/controllers/auth.py:448
msgid "PASSWORD_INCORRECT"
msgstr ""

#: src/backend/controllers/auth.py:453
msgid "AUTH_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:453
msgid "VALID_TOKEN_OR_USER_WS_MANDATORY"
msgstr ""

#: src/backend/controllers/auth.py:484
msgid "SEVERAL_AUTH_METHODS_ENABLED"
msgstr ""

#: src/backend/controllers/auth.py:508
msgid "LDAP_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:509 src/backend/models/auth.py:140
msgid "NO_LDAP_CONFIGURATIONS_FOUND"
msgstr ""

#: src/backend/controllers/auth.py:535
msgid "LOADING_METHODS_AUTH_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:547
msgid "DISABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:559
msgid "ENABLE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:589 src/backend/controllers/auth.py:776
#: src/backend/controllers/auth.py:832 src/backend/controllers/auth.py:847
#: src/backend/controllers/auth.py:855 src/backend/controllers/auth.py:861
msgid "LDAP_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:590
msgid "LOGIN_LDAP_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:764 src/backend/controllers/auth.py:770
msgid "LDAP_SYNCHRO_INFOS_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:766 src/backend/controllers/auth.py:772
#: src/backend/controllers/auth.py:778 src/backend/controllers/auth.py:784
#: src/backend/controllers/auth.py:790
msgid "LDAP_SYNCHRO_ERROR"
msgstr ""

#: src/backend/controllers/auth.py:782 src/backend/controllers/auth.py:788
#: src/backend/controllers/auth.py:867 src/backend/rest/auth.py:182
msgid "INFOS_LDAP_NOT_COMPLETE"
msgstr ""

#: src/backend/controllers/auth.py:830 src/backend/controllers/auth.py:845
#: src/backend/controllers/auth.py:853
msgid "BAD_CONNECTION_LDAP_INFOS"
msgstr ""

#: src/backend/controllers/auth.py:865 src/backend/rest/auth.py:183
msgid "NOT_COMPLETE_CONNECTION_INFOS"
msgstr ""

#: src/backend/controllers/config.py:64
msgid "LANGUAGE_CHANGED"
msgstr ""

#: src/backend/controllers/config.py:79
msgid "RETRIEVE_CONFIGURATION_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:109
msgid "RETRIEVE_CONFIGURATIONS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:139
msgid "RETRIEVE_DOCSERVERS_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:177
msgid "RETRIEVE_REGEX_ERRORS"
msgstr ""

#: src/backend/controllers/config.py:189 src/backend/controllers/config.py:218
#: src/backend/controllers/config.py:230 src/backend/controllers/config.py:257
#: src/backend/models/config.py:199 src/backend/models/config.py:223
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr ""

#: src/backend/controllers/config.py:190 src/backend/controllers/config.py:231
msgid "JWT_EXPIRATION_COULDNT_BE_ZERO_OR_LESS"
msgstr ""

#: src/backend/controllers/config.py:213 src/backend/controllers/config.py:252
msgid "UPDATE_CONFIGURATION"
msgstr ""

#: src/backend/controllers/config.py:280
msgid "UPDATE_REGEX"
msgstr ""

#: src/backend/controllers/config.py:285 src/backend/models/config.py:245
msgid "UPDATE_REGEX_ERROR"
msgstr ""

#: src/backend/controllers/config.py:307
msgid "UPDATE_DOCSERVER"
msgstr ""

#: src/backend/controllers/config.py:312 src/backend/models/config.py:271
msgid "UPDATE_DOCSERVER_ERROR"
msgstr ""

#: src/backend/controllers/config.py:354 src/backend/controllers/config.py:370
#: src/backend/controllers/config.py:375
msgid "ERROR_UPDATING_IMAGE"
msgstr ""

#: src/backend/controllers/config.py:355 src/backend/controllers/config.py:371
msgid "CUSTOM_IMAGE_PATH_NOT_WRITEABLE_OR_NOT_EXISTS"
msgstr ""

#: src/backend/controllers/config.py:365
msgid "UPDATE_LOGIN_IMAGE"
msgstr ""

#: src/backend/controllers/config.py:376
msgid "CUSTOM_NOT_PRESENT"
msgstr ""

#: src/backend/controllers/custom_fields.py:33
#: src/backend/controllers/custom_fields.py:49
#: src/backend/controllers/custom_fields.py:62
msgid "CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/custom_fields.py:75
msgid "CUSTOM_FIELDS_DELETE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:39
#: src/backend/controllers/doctypes.py:81 src/backend/models/doctypes.py:131
#: src/backend/models/doctypes.py:134
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:45 src/backend/models/doctypes.py:51
msgid "ADD_DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:65
#: src/backend/controllers/doctypes.py:101
#: src/backend/controllers/doctypes.py:114
#: src/backend/controllers/doctypes.py:166
#: src/backend/controllers/doctypes.py:197
#: src/backend/controllers/doctypes.py:236
#: src/backend/controllers/doctypes.py:265
#: src/backend/controllers/doctypes.py:291
#: src/backend/controllers/doctypes.py:320 src/backend/controllers/user.py:556
msgid "DOCTYPE_ERROR"
msgstr ""

#: src/backend/controllers/doctypes.py:133
msgid "BUNDLESEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:140
msgid "DOCUMENTSEPARATOR"
msgstr ""

#: src/backend/controllers/doctypes.py:159
msgid "DOCTYPESEPARATOR"
msgstr ""

#: src/backend/controllers/forms.py:72 src/backend/controllers/forms.py:106
#: src/backend/controllers/forms.py:229
msgid "FORMS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:101
msgid "CREATE_FORM"
msgstr ""

#: src/backend/controllers/forms.py:121 src/backend/controllers/forms.py:170
#: src/backend/models/forms.py:66
msgid "GET_FORM_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:153
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:218
msgid "UPDATE_FORM"
msgstr ""

#: src/backend/controllers/forms.py:223 src/backend/controllers/forms.py:381
#: src/backend/controllers/forms.py:387
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:245
msgid "DELETE_FORM"
msgstr ""

#: src/backend/controllers/forms.py:250 src/backend/controllers/forms.py:256
msgid "DELETE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:265 src/backend/controllers/outputs.py:66
#: src/backend/controllers/positions_masks.py:165
#: src/backend/controllers/workflow.py:120
msgid "COPY_OF"
msgstr ""

#: src/backend/controllers/forms.py:286
msgid "DUPLICATE_FORM"
msgstr ""

#: src/backend/controllers/forms.py:291 src/backend/controllers/forms.py:297
msgid "DUPLICATE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:313
msgid "DISABLE_FORM"
msgstr ""

#: src/backend/controllers/forms.py:318 src/backend/controllers/forms.py:324
msgid "DISABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:340
msgid "ENABLE_FORM"
msgstr ""

#: src/backend/controllers/forms.py:345 src/backend/controllers/forms.py:351
msgid "ENABLE_FORM_ERROR"
msgstr ""

#: src/backend/controllers/forms.py:367
msgid "GET_FORMS_FIELDS_ERROR"
msgstr ""

#: src/backend/controllers/history.py:31
msgid "ADD_HISTORY_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:38
msgid "RETRIEVE_PROCESSES_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:53
msgid "UPDATE_MAILCOLLECT_PROCESS"
msgstr ""

#: src/backend/controllers/mailcollect.py:61
msgid "UPDATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:76
msgid "CREATE_MAILCOLLECT_PROCESS"
msgstr ""

#: src/backend/controllers/mailcollect.py:84
msgid "CREATE_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:100
msgid "DELETE_MAILCOLLECT_PROCESS"
msgstr ""

#: src/backend/controllers/mailcollect.py:105
#: src/backend/controllers/mailcollect.py:111
msgid "DELETE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:127
msgid "ENABLE_MAILCOLLECT_PROCESS"
msgstr ""

#: src/backend/controllers/mailcollect.py:132
#: src/backend/controllers/mailcollect.py:138
msgid "ENABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:154
msgid "DISABLE_MAILCOLLECT_PROCESS"
msgstr ""

#: src/backend/controllers/mailcollect.py:159
#: src/backend/controllers/mailcollect.py:165
msgid "DISABLE_MAILCOLLECT_PROCESS_ERROR"
msgstr ""

#: src/backend/controllers/mailcollect.py:179
#: src/backend/controllers/mailcollect.py:189
msgid "MAILCOLLECT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:75
msgid "DUPLICATE_OUTPUT"
msgstr ""

#: src/backend/controllers/outputs.py:80 src/backend/controllers/outputs.py:86
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:115
#: src/backend/controllers/outputs.py:144
#: src/backend/controllers/outputs.py:150
msgid "UPDATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:116
msgid "NOT_ALLOWED_OUTPUT_PATH"
msgstr ""

#: src/backend/controllers/outputs.py:139
msgid "UPDATE_OUTPUT"
msgstr ""

#: src/backend/controllers/outputs.py:173
msgid "CREATE_OUTPUT"
msgstr ""

#: src/backend/controllers/outputs.py:181
msgid "CREATE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:194
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:207
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:223
msgid "DELETE_OUTPUT"
msgstr ""

#: src/backend/controllers/outputs.py:228
#: src/backend/controllers/outputs.py:234
msgid "DELETE_OUTPUT_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:262
#: src/backend/controllers/outputs.py:271
#: src/backend/controllers/outputs.py:278
msgid "OUTPUT_FOLDER_CREATION_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:263
#: src/backend/controllers/workflow.py:65
msgid "FOLDER_NOT_ALLOWED_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:272
#: src/backend/controllers/workflow.py:74
#: src/backend/controllers/workflow.py:395
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr ""

#: src/backend/controllers/outputs.py:279
#: src/backend/controllers/workflow.py:81
msgid "CAN_NOT_ACCESS_FOLDER_PERMISSION_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:43
#: src/backend/controllers/positions_masks.py:74
#: src/backend/controllers/positions_masks.py:123
#: src/backend/controllers/positions_masks.py:129
msgid "POSITION_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:65
msgid "CREATE_POSITIONS_MASK"
msgstr ""

#: src/backend/controllers/positions_masks.py:89
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:118
msgid "UPDATE_POSITIONS_MASK"
msgstr ""

#: src/backend/controllers/positions_masks.py:145
#: src/backend/controllers/positions_masks.py:230
msgid "DELETE_POSITIONS_MASK"
msgstr ""

#: src/backend/controllers/positions_masks.py:150
#: src/backend/controllers/positions_masks.py:156
msgid "DELETE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:181
#: src/backend/controllers/positions_masks.py:187
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:203
msgid "DISABLE_POSITIONS_MASK"
msgstr ""

#: src/backend/controllers/positions_masks.py:208
#: src/backend/controllers/positions_masks.py:214
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:235
#: src/backend/controllers/positions_masks.py:241
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:264
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:287
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:305
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/positions_masks.py:323
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr ""

#: src/backend/controllers/privileges.py:38
#: src/backend/controllers/privileges.py:66
#: src/backend/controllers/privileges.py:94
msgid "GET_PRIVILEGES_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:39 src/backend/controllers/user.py:122
#: src/backend/controllers/user.py:138 src/backend/controllers/user.py:219
#: src/backend/models/user.py:140 src/backend/models/user.py:187
msgid "GET_USER_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:49 src/backend/controllers/roles.py:169
msgid "GET_ROLE_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:88
msgid "UPDATE_ROLE"
msgstr ""

#: src/backend/controllers/roles.py:93 src/backend/controllers/roles.py:99
#: src/backend/controllers/roles.py:150 src/backend/controllers/roles.py:156
#: src/backend/models/roles.py:85
msgid "UPDATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:121
msgid "CREATE_ROLE"
msgstr ""

#: src/backend/controllers/roles.py:130 src/backend/models/roles.py:105
msgid "CREATE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:185
msgid "DELETE_ROLE"
msgstr ""

#: src/backend/controllers/roles.py:190 src/backend/controllers/roles.py:196
msgid "DELETE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:210 src/backend/controllers/roles.py:216
msgid "DISABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/roles.py:230 src/backend/controllers/roles.py:236
msgid "ENABLE_ROLE_ERROR"
msgstr ""

#: src/backend/controllers/smtp.py:49
msgid "SMTP_TEST_SEND_EMAIL_ERROR"
msgstr ""

#: src/backend/controllers/smtp.py:55
msgid "SMTP_TEST_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:114
msgid "LOAD_METADATA_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:170
#: src/backend/controllers/verifier.py:125
msgid "AT"
msgstr ""

#: src/backend/controllers/splitter.py:194
msgid "FORM_UNDEFINED"
msgstr ""

#: src/backend/controllers/splitter.py:197
msgid "CUSTOMER_UNDEFINED"
msgstr ""

#: src/backend/controllers/splitter.py:255
#: src/backend/controllers/splitter.py:286
msgid "BATCH_NOT_FOUND"
msgstr ""

#: src/backend/controllers/splitter.py:256
#: src/backend/controllers/splitter.py:287
msgid "BATCH_ID_NOT_FOUND"
msgstr ""

#: src/backend/controllers/splitter.py:270
msgid "DELETE_BATCH_SUCCESS"
msgstr ""

#: src/backend/controllers/splitter.py:275
#: src/backend/controllers/splitter.py:296
#: src/backend/controllers/verifier.py:784
msgid "UPDATE_STATUS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:331
#: src/backend/controllers/verifier.py:402
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:433
msgid "ADD_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:459
msgid "UPDATE_BATCH_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:472
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:485
#: src/backend/controllers/verifier.py:379
#: src/backend/controllers/verifier.py:385
msgid "UPDATE_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:500
#: src/backend/controllers/splitter.py:521
#: src/backend/controllers/splitter.py:536
#: src/backend/controllers/splitter.py:551
msgid "UPDATE_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:565
msgid "CMIS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:578
msgid "OPENADS_CONNECTION_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:678
#: src/backend/controllers/verifier.py:763 src/backend/models/splitter.py:572
#: src/backend/models/verifier.py:195
msgid "GET_TOTALS_ERROR"
msgstr ""

#: src/backend/controllers/splitter.py:777
msgid "GET_BATCH_OUTPUTS_ERROR"
msgstr ""

#: src/backend/controllers/status.py:31
msgid "RETRIEVES_STATUS_ERROR"
msgstr ""

#: src/backend/controllers/user.py:73
msgid "CREATE_USER"
msgstr ""

#: src/backend/controllers/user.py:78
msgid "CREATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:155
msgid "GET_USER_BY_USERNAME_ERROR"
msgstr ""

#: src/backend/controllers/user.py:181
msgid "USER_FORGOT_SUCCESS"
msgstr ""

#: src/backend/controllers/user.py:186
msgid "SEND_EMAIL_FORGOT_PASSWORD_ERROR"
msgstr ""

#: src/backend/controllers/user.py:209
msgid "USER_RESET_PASSWORD_SUCCESS"
msgstr ""

#: src/backend/controllers/user.py:213 src/backend/controllers/user.py:218
msgid "RESET_PASSWORD_ERROR"
msgstr ""

#: src/backend/controllers/user.py:214
msgid "RESET_TOKEN_MISMATCH"
msgstr ""

#: src/backend/controllers/user.py:299
msgid "UPDATE_PROFILE"
msgstr ""

#: src/backend/controllers/user.py:300
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:306
msgid "UPDATE_USER"
msgstr ""

#: src/backend/controllers/user.py:307
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr ""

#: src/backend/controllers/user.py:337
msgid "USER_UPDATED"
msgstr ""

#: src/backend/controllers/user.py:342 src/backend/controllers/user.py:348
#: src/backend/models/user.py:255 src/backend/models/user.py:321
msgid "UPDATE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:364
msgid "DELETE_USER"
msgstr ""

#: src/backend/controllers/user.py:372 src/backend/controllers/user.py:378
msgid "DELETE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:394
msgid "DISABLE_USER"
msgstr ""

#: src/backend/controllers/user.py:402 src/backend/controllers/user.py:408
msgid "DISABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:424
msgid "ENABLE_USER"
msgstr ""

#: src/backend/controllers/user.py:432 src/backend/controllers/user.py:438
msgid "ENABLE_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:455 src/backend/controllers/user.py:461
#: src/backend/models/user.py:277
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:476 src/backend/controllers/user.py:483
#: src/backend/models/user.py:299
msgid "UPDATE_FORMS_USER_ERROR"
msgstr ""

#: src/backend/controllers/user.py:527
msgid "USER_EXPORT_ERROR"
msgstr ""

#: src/backend/controllers/user.py:572
msgid "GET_DEFAULT_ROUTE_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:89 src/backend/models/splitter.py:219
#: src/backend/models/verifier.py:40
msgid "GET_DOCUMENT_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:106 src/backend/models/verifier.py:64
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:107
msgid "GET_DOCUMENT_ID_AND_STATUS_BY_TOKEN_ERROR_MESSAGE"
msgstr ""

#: src/backend/controllers/verifier.py:217
#: src/backend/controllers/verifier.py:319
msgid "UPDATE_DOCUMENT_POSITIONS_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:240
#: src/backend/controllers/verifier.py:337
msgid "UPDATE_DOCUMENT_PAGES_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:263
#: src/backend/controllers/verifier.py:281
msgid "UPDATE_DOCUMENT_DATA_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:353
msgid "DELETE_DOCUMENT_SUCCESS"
msgstr ""

#: src/backend/controllers/verifier.py:358
#: src/backend/controllers/verifier.py:364
msgid "DELETE_DOCUMENT_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:492
#: src/backend/controllers/workflow.py:228
#: src/backend/controllers/workflow.py:297
#: src/backend/controllers/workflow.py:486 src/backend/process/main.py:41
msgid "SCRIPT_CONTAINS_NOT_ALLOWED_CODE"
msgstr ""

#: src/backend/controllers/verifier.py:656
#: src/backend/controllers/verifier.py:659
#: src/backend/controllers/verifier.py:676
#: src/backend/controllers/verifier.py:702
#: src/backend/controllers/verifier.py:703
msgid "API_INSEE_ERROR_CONNEXION"
msgstr ""

#: src/backend/controllers/verifier.py:733
msgid "VAT_NOT_VALID"
msgstr ""

#: src/backend/controllers/verifier.py:740
#: src/backend/controllers/verifier.py:741
msgid "VAT_API_ERROR"
msgstr ""

#: src/backend/controllers/verifier.py:774
msgid "DOCUMENT_NOT_FOUND"
msgstr ""

#: src/backend/controllers/verifier.py:775
msgid "DOCUMENT_ID_NOT_FOUND"
msgstr ""

#: src/backend/controllers/verifier.py:830
msgid "NO_FORM"
msgstr ""

#: src/backend/controllers/workflow.py:64
#: src/backend/controllers/workflow.py:73
#: src/backend/controllers/workflow.py:80
msgid "WORKFLOW_FOLDER_CREATION_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:95
msgid "GET_WORKFLOW_BY_ID_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:108
msgid "GET_WORKFLOW_BY_WORKFLOW_ID_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:133
msgid "DUPLICATE_WORKFLOW"
msgstr ""

#: src/backend/controllers/workflow.py:138
#: src/backend/controllers/workflow.py:144
msgid "DUPLICATE_WORKFLOW_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:169
#: src/backend/controllers/workflow.py:181
#: src/backend/controllers/workflow.py:192
#: src/backend/controllers/workflow.py:227
#: src/backend/controllers/workflow.py:247
msgid "CREATE_WORKFLOW_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:170
#: src/backend/controllers/workflow.py:257
msgid "NOT_ALLOWED_INPUT_PATH"
msgstr ""

#: src/backend/controllers/workflow.py:182
msgid "WORKFLOW_ID_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/workflow.py:193
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr ""

#: src/backend/controllers/workflow.py:239
msgid "CREATE_WORKFLOW"
msgstr ""

#: src/backend/controllers/workflow.py:256
#: src/backend/controllers/workflow.py:296
#: src/backend/controllers/workflow.py:313
#: src/backend/controllers/workflow.py:319
msgid "UPDATE_WORKFLOW_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:308
msgid "UPDATE_WORKFLOW"
msgstr ""

#: src/backend/controllers/workflow.py:336
msgid "DELETE_WORKFLOW"
msgstr ""

#: src/backend/controllers/workflow.py:341
#: src/backend/controllers/workflow.py:347
msgid "DELETE_WORKFLOW_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:394
#: src/backend/controllers/workflow.py:416
msgid "FS_WATCHER_CREATION_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:417
#: src/backend/controllers/workflow.py:470
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr ""

#: src/backend/controllers/workflow.py:422
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/workflow.py:428
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr ""

#: src/backend/controllers/workflow.py:469
msgid "FS_WATCHER_DELETION_ERROR"
msgstr ""

#: src/backend/controllers/workflow.py:496
msgid "LINE"
msgstr ""

#: src/backend/controllers/workflow.py:497
msgid "COLUMN"
msgstr ""

#: src/backend/models/accounts.py:105
msgid "SUPPLIER_UPDATE_ERROR"
msgstr ""

#: src/backend/models/artificial_intelligence.py:80
msgid "IA_MODEL_CREATE_ERROR"
msgstr ""

#: src/backend/models/artificial_intelligence.py:101
msgid "IA_MODEL_UPDATE_ERROR"
msgstr ""

#: src/backend/models/auth.py:43 src/backend/models/auth.py:101
#: src/backend/models/user.py:43 src/backend/rest/auth.py:83
msgid "BAD_USERNAME"
msgstr ""

#: src/backend/models/auth.py:45 src/backend/models/user.py:45
msgid "BAD_PASSWORD"
msgstr ""

#: src/backend/models/auth.py:47
msgid "USER_DELETED"
msgstr ""

#: src/backend/models/auth.py:49
msgid "USER_DISABLED"
msgstr ""

#: src/backend/models/auth.py:70 src/backend/models/auth.py:80
#: src/backend/models/roles.py:61
msgid "ROLE_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/auth.py:165
msgid "UPDATE_LOGIN_METHOD_ERROR"
msgstr ""

#: src/backend/models/auth.py:211
msgid "DISABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/auth.py:233
msgid "ENABLE_LOGIN_METHOD_DATA_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:57
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:60
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr ""

#: src/backend/models/custom_fields.py:110
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/custom_fields.py:133
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/doctypes.py:54
msgid "DOCTYPE_ALREADY_EXIST"
msgstr ""

#: src/backend/models/doctypes.py:100
msgid "UPDATE_DOCTYPE_ERROR"
msgstr ""

#: src/backend/models/forms.py:45
msgid "GET_FORMS_ERROR"
msgstr ""

#: src/backend/models/forms.py:89
msgid "GET_FORM_SETTINGS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/forms.py:112
msgid "GET_DEFAULT_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:136
msgid "UPDATE_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:158
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr ""

#: src/backend/models/forms.py:215
msgid "ADD_FORM_ERROR"
msgstr ""

#: src/backend/models/forms.py:218
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/mailcollect.py:85
msgid "MAILCOLLECT_PROCESS_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:78
msgid "OUTPUT_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/outputs.py:125
msgid "OUTPUT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/outputs.py:145
msgid "OUTPUT_CREATE_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:63
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:87
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:109
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:144
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr ""

#: src/backend/models/positions_masks.py:147
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr ""

#: src/backend/models/privileges.py:38 src/backend/models/privileges.py:59
#: src/backend/models/privileges.py:83
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr ""

#: src/backend/models/roles.py:127
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr ""

#: src/backend/models/roles.py:149
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:78
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/splitter.py:125
msgid "UPDATE_SETTINGS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:150
msgid "INSERT_PAGE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:244
msgid "GET_DOCUMENTS_ERROR"
msgstr ""

#: src/backend/models/splitter.py:266 src/backend/models/splitter.py:289
msgid "GET_PAGES_ERROR"
msgstr ""

#: src/backend/models/splitter.py:311
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr ""

#: src/backend/models/splitter.py:334
msgid "GET_DOCUMENT_ERROR"
msgstr ""

#: src/backend/models/splitter.py:356
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr ""

#: src/backend/models/status.py:40
msgid "NO_STATUS"
msgstr ""

#: src/backend/models/user.py:47
msgid "USER"
msgstr ""

#: src/backend/models/user.py:47
msgid "ALREADY_REGISTERED"
msgstr ""

#: src/backend/models/user.py:163
msgid "GET_USER_BY_MAIL_ERROR"
msgstr ""

#: src/backend/models/user.py:232
msgid "GET_FORMS_BY_USER_ID_ERROR"
msgstr ""

#: src/backend/models/verifier.py:128 src/backend/models/verifier.py:149
msgid "DOCUMENT_UPDATE_ERROR"
msgstr ""

#: src/backend/models/workflow.py:60 src/backend/models/workflow.py:83
msgid "WORKFLOW_DOESNT_EXISTS"
msgstr ""

#: src/backend/models/workflow.py:105
msgid "WORKFLOW_CREATE_ERROR"
msgstr ""

#: src/backend/models/workflow.py:127
msgid "WORKFLOW_UPDATE_ERROR"
msgstr ""

#: src/backend/rest/accounts.py:35 src/backend/rest/accounts.py:56
#: src/backend/rest/accounts.py:69 src/backend/rest/accounts.py:81
#: src/backend/rest/accounts.py:118 src/backend/rest/accounts.py:140
#: src/backend/rest/accounts.py:162 src/backend/rest/accounts.py:188
#: src/backend/rest/accounts.py:215 src/backend/rest/accounts.py:249
#: src/backend/rest/accounts.py:284 src/backend/rest/accounts.py:295
#: src/backend/rest/accounts.py:306 src/backend/rest/accounts.py:335
#: src/backend/rest/accounts.py:364 src/backend/rest/accounts.py:376
#: src/backend/rest/accounts.py:398 src/backend/rest/accounts.py:409
#: src/backend/rest/accounts.py:435 src/backend/rest/accounts.py:460
#: src/backend/rest/accounts.py:504
#: src/backend/rest/artificial_intelligence.py:30
#: src/backend/rest/artificial_intelligence.py:40
#: src/backend/rest/artificial_intelligence.py:51
#: src/backend/rest/artificial_intelligence.py:61
#: src/backend/rest/artificial_intelligence.py:72
#: src/backend/rest/artificial_intelligence.py:90
#: src/backend/rest/artificial_intelligence.py:105
#: src/backend/rest/artificial_intelligence.py:117 src/backend/rest/auth.py:113
#: src/backend/rest/auth.py:163 src/backend/rest/auth.py:173
#: src/backend/rest/auth.py:193 src/backend/rest/auth.py:204
#: src/backend/rest/auth.py:227 src/backend/rest/auth.py:246
#: src/backend/rest/config.py:31 src/backend/rest/config.py:41
#: src/backend/rest/config.py:51 src/backend/rest/config.py:61
#: src/backend/rest/config.py:72 src/backend/rest/config.py:82
#: src/backend/rest/config.py:92 src/backend/rest/config.py:109
#: src/backend/rest/config.py:120 src/backend/rest/config.py:131
#: src/backend/rest/config.py:143 src/backend/rest/custom_fields.py:32
#: src/backend/rest/custom_fields.py:46 src/backend/rest/custom_fields.py:57
#: src/backend/rest/custom_fields.py:68 src/backend/rest/custom_fields.py:78
#: src/backend/rest/doctypes.py:31 src/backend/rest/doctypes.py:47
#: src/backend/rest/doctypes.py:58 src/backend/rest/doctypes.py:69
#: src/backend/rest/doctypes.py:80 src/backend/rest/doctypes.py:90
#: src/backend/rest/doctypes.py:101 src/backend/rest/doctypes.py:116
#: src/backend/rest/forms.py:33 src/backend/rest/forms.py:47
#: src/backend/rest/forms.py:59 src/backend/rest/forms.py:92
#: src/backend/rest/forms.py:103 src/backend/rest/forms.py:115
#: src/backend/rest/forms.py:126 src/backend/rest/forms.py:138
#: src/backend/rest/forms.py:149 src/backend/rest/forms.py:160
#: src/backend/rest/forms.py:171 src/backend/rest/forms.py:183
#: src/backend/rest/history.py:39 src/backend/rest/history.py:49
#: src/backend/rest/history.py:59 src/backend/rest/locale.py:31
#: src/backend/rest/mailcollect.py:29 src/backend/rest/mailcollect.py:45
#: src/backend/rest/mailcollect.py:56 src/backend/rest/mailcollect.py:72
#: src/backend/rest/mailcollect.py:86 src/backend/rest/mailcollect.py:97
#: src/backend/rest/mailcollect.py:108 src/backend/rest/monitoring.py:29
#: src/backend/rest/monitoring.py:39 src/backend/rest/monitoring.py:49
#: src/backend/rest/monitoring.py:60 src/backend/rest/outputs.py:32
#: src/backend/rest/outputs.py:45 src/backend/rest/outputs.py:64
#: src/backend/rest/outputs.py:76 src/backend/rest/outputs.py:88
#: src/backend/rest/outputs.py:101 src/backend/rest/outputs.py:113
#: src/backend/rest/outputs.py:125 src/backend/rest/outputs.py:136
#: src/backend/rest/positions_masks.py:33
#: src/backend/rest/positions_masks.py:43
#: src/backend/rest/positions_masks.py:54
#: src/backend/rest/positions_masks.py:65
#: src/backend/rest/positions_masks.py:77
#: src/backend/rest/positions_masks.py:89
#: src/backend/rest/positions_masks.py:101
#: src/backend/rest/positions_masks.py:112
#: src/backend/rest/positions_masks.py:123
#: src/backend/rest/positions_masks.py:134
#: src/backend/rest/positions_masks.py:145
#: src/backend/rest/positions_masks.py:157 src/backend/rest/privileges.py:29
#: src/backend/rest/privileges.py:39 src/backend/rest/roles.py:43
#: src/backend/rest/roles.py:53 src/backend/rest/roles.py:64
#: src/backend/rest/roles.py:75 src/backend/rest/roles.py:85
#: src/backend/rest/roles.py:95 src/backend/rest/roles.py:105
#: src/backend/rest/splitter.py:30 src/backend/rest/splitter.py:52
#: src/backend/rest/splitter.py:62 src/backend/rest/splitter.py:72
#: src/backend/rest/splitter.py:83 src/backend/rest/splitter.py:98
#: src/backend/rest/splitter.py:109 src/backend/rest/splitter.py:119
#: src/backend/rest/splitter.py:130 src/backend/rest/splitter.py:144
#: src/backend/rest/splitter.py:155 src/backend/rest/splitter.py:166
#: src/backend/rest/splitter.py:177 src/backend/rest/splitter.py:196
#: src/backend/rest/splitter.py:207 src/backend/rest/splitter.py:222
#: src/backend/rest/splitter.py:225 src/backend/rest/splitter.py:243
#: src/backend/rest/splitter.py:255 src/backend/rest/splitter.py:266
#: src/backend/rest/splitter.py:277 src/backend/rest/splitter.py:287
#: src/backend/rest/splitter.py:298 src/backend/rest/status.py:31
#: src/backend/rest/user.py:30 src/backend/rest/user.py:41
#: src/backend/rest/user.py:66 src/backend/rest/user.py:76
#: src/backend/rest/user.py:108 src/backend/rest/user.py:119
#: src/backend/rest/user.py:129 src/backend/rest/user.py:139
#: src/backend/rest/user.py:156 src/backend/rest/user.py:167
#: src/backend/rest/user.py:177 src/backend/rest/user.py:188
#: src/backend/rest/user.py:203 src/backend/rest/verifier.py:45
#: src/backend/rest/verifier.py:96 src/backend/rest/verifier.py:108
#: src/backend/rest/verifier.py:129 src/backend/rest/verifier.py:142
#: src/backend/rest/verifier.py:154 src/backend/rest/verifier.py:166
#: src/backend/rest/verifier.py:179 src/backend/rest/verifier.py:192
#: src/backend/rest/verifier.py:205 src/backend/rest/verifier.py:218
#: src/backend/rest/verifier.py:231 src/backend/rest/verifier.py:244
#: src/backend/rest/verifier.py:255 src/backend/rest/verifier.py:274
#: src/backend/rest/verifier.py:293 src/backend/rest/verifier.py:313
#: src/backend/rest/verifier.py:325 src/backend/rest/verifier.py:337
#: src/backend/rest/verifier.py:360 src/backend/rest/verifier.py:379
#: src/backend/rest/verifier.py:391 src/backend/rest/verifier.py:402
#: src/backend/rest/verifier.py:415 src/backend/rest/verifier.py:428
#: src/backend/rest/verifier.py:439 src/backend/rest/verifier.py:452
#: src/backend/rest/verifier.py:463 src/backend/rest/verifier.py:478
#: src/backend/rest/workflow.py:32 src/backend/rest/workflow.py:44
#: src/backend/rest/workflow.py:68 src/backend/rest/workflow.py:83
#: src/backend/rest/workflow.py:95 src/backend/rest/workflow.py:107
#: src/backend/rest/workflow.py:119 src/backend/rest/workflow.py:131
#: src/backend/rest/workflow.py:153 src/backend/rest/workflow.py:166
#: src/backend/rest/workflow.py:177
msgid "UNAUTHORIZED_ROUTE"
msgstr ""

#: src/backend/rest/accounts.py:44 src/backend/rest/accounts.py:104
#: src/backend/rest/accounts.py:126 src/backend/rest/accounts.py:148
#: src/backend/rest/accounts.py:175 src/backend/rest/accounts.py:201
#: src/backend/rest/accounts.py:227 src/backend/rest/accounts.py:272
#: src/backend/rest/accounts.py:316 src/backend/rest/accounts.py:345
#: src/backend/rest/accounts.py:386 src/backend/rest/accounts.py:423
#: src/backend/rest/accounts.py:448 src/backend/rest/auth.py:38
#: src/backend/rest/auth.py:100 src/backend/rest/auth.py:122
#: src/backend/rest/auth.py:142 src/backend/rest/auth.py:234
#: src/backend/rest/auth.py:253 src/backend/rest/outputs.py:144
#: src/backend/rest/workflow.py:53 src/backend/rest/workflow.py:141
#: src/backend/rest/workflow.py:184
msgid "BAD_REQUEST"
msgstr ""

#: src/backend/rest/auth.py:58 src/backend/rest/auth.py:87
msgid "PGSQL_ERROR"
msgstr ""

#: src/backend/rest/auth.py:209
msgid "REQUEST_MODIFS_ERROR"
msgstr ""

#: src/backend/rest/monitoring.py:65 src/backend/rest/verifier.py:121
msgid "TOKEN_IS_MANDATORY"
msgstr ""

#: src/backend/rest/splitter.py:45 src/backend/rest/verifier.py:89
msgid "UNKNOW_ERROR"
msgstr ""

#: src/backend/rest/verifier.py:50
msgid "VERIFIER_UPLOAD_ERROR"
msgstr ""

#: src/backend/rest/verifier.py:51
msgid "WORKFLOW_ID_IS_MANDATORY"
msgstr ""

#: src/backend/rest/verifier.py:84
msgid "UNIQUE_URL_TOKEN_GENERATION_ERROR"
msgstr ""

#: src/backend/rest/verifier.py:85
msgid "INTERFACE_IS_NOT_USED_OR_FORM_UNIQUE_URL_NOT_SET"
msgstr ""

